version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=nest_graphql_training
      - POSTGRES_DB=nest_graphql_training
      - POSTGRES_PASSWORD=nest_graphql_training
      - TZ=Asia/Tokyo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
